import = [
    "~/dotfiles/argonaut.toml"
]

[window]
dimensions = { columns = 80, lines = 24 }
opacity = 0.95
resize_increments = true

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Retina" }
size = 14
offset = { y = 2 }

[colors.primary]
background = "#181818"

[keyboard]
bindings = [
    { key = "T", mods = "Control | Shift", action = "CreateNewWindow" },
	{ key = "W", mods = "Control | Shift", action = "Quit" }
]